firebase emulator requires Java 21+
```
$ firebase --project test emulators:exec --only firestore "bundle exec rspec"

Error: firebase-tools no longer supports Java version before 21. Please install a JDK at version 21 or above to get a compatible runtime.
Error: Process completed with exit code 1.
```

https://github.com/sue445/kagaribi/actions/runs/20163233900/job/57880379353

Close #69